name: cs-storage-dev
channels:
  - conda-forge
dependencies:
  - "marshmallow>=3.0.0"
  - pytest
  - gcsfs
  - jinja2 # optional
  - pyppeteer # optional
  - bokeh # optional
  - websockets # optional
