name: cs-storage-dev
channels:
  - conda-forge
dependencies:
  - "marshmallow>=3.0.0"
  - pytest
  - gcsfs
  - jinja2 # optional
  - bokeh # optional
  - websockets # optional
  - matplotlib
  - numpy
  - "pillow<7"
  - pip
  - pip:
      - pyppeteer2 # optional
      # - git+https://github.com/pyppeteer/pyppeteer@pup2.1.1 # includes pyee bug fix
